apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: schoolofdevops/vote:v3
