apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - name: "80"
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30200
  selector:
    app: vote
